export const API_KEY = `d31522a945d5fb0d2fcf11ca7edc52a8`;
export const DaysApiLeft = `https://api.openweathermap.org/data/2.5/forecast?q=`;
export const DaysApiRight = `&appid=${API_KEY}&units=metric`;
export const weatherApiLeft = `https://api.openweathermap.org/data/2.5/weather?q=`;
export const weatherApiRight = `&appid=${API_KEY}&units=metric`;
export const APIMAP_KEY = `MxOdkoWsS3jMJikgMYSAllHMRLq00rVz`;
export const userLocationLinkleft = `https://www.mapquestapi.com/geocoding/v1/reverse?key=${APIMAP_KEY}&location=`
export const userLocationLinkRight = `&includeRoadMetadata=true&includeNearestIntersection=true`
export const LoaderUserLocationL = `https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid=${API_KEY}&units=metric`